hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
spring:
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411/
  sleuth:
      sampler:
        probability: 1