eureka:
  client:
    service-url.defaultZone: http://eureka.server.ip:8761/eureka
  instance:
    prefer-ip-address: true
    metadata-map:
      user.name: 'admin'
      user.password: '123456'
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/a46461440/study-config
          username: 496461440@qq.com
          password: Aa412629
          basedir: F:/cloud-config-basedir/
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
  security:
    user:
      name: admin
      password: 123456
server:
  port: 1302
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'