spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Aa412629
    url: jdbc:mysql://47.96.18.57:3306/springCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
      show-sql: true
eureka:
  client:
    service-url:
      defaultUrl: http://server1:8761/eureka
server:
  port: 1201
