hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
spring:
  security:
    user:
      name: admin
      password: 123456
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411/
  sleuth:
      sampler:
        probability: 1
  resources:
    chain:
      enabled: true