spring:
  security:
    user:
      name: admin
      password: 123456
  zipkin:
    sender:
      type: web
    base-url: http://zipkin.ip:9411/
  sleuth:
      sampler:
        probability: 1
  boot:
    admin:
      notify:
        pagerduty:
          client: ADMIN
management:
  endpoints:
    web:
      exposure:
        include: '*'