spring:
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411/
  sleuth:
      sampler:
        probability: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  ReadTimeout: 5000