spring:
#  security:
#      user:
#        name: admin
#        password: 123456
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411/
  sleuth:
      sampler:
        probability: 1